---
title: "EucFACE vegetation with environmental variables"
author: "Shun Hasegawa"
date: "Thursday, May 07, 2015"
output: pdf_document
---


```{r, include=FALSE}
source("../R/Packages.R")
# source("../R/functions.R")

# Environmental variables
load("../output//Data/FACE_EnvironmenVars.RData")

# Raw data for multi variate analysis
load("../output/Data//FACE_Vegetation_Raw_2013_2015.RData")

# Data frame with plant functional groups
load("../output//Data//FACE_Vegetation_PFG_2015.RData")

# check unknown spp
all(!grepl("unknown", VegRes15$variable, ignore.case = TRUE))

# co2, block and id
veg <- within(VegRes15, {
  block <- recode(ring, "1:2 = 'A'; 3:4 = 'B'; 5:6 = 'C'")
  co2 <- factor(ifelse(ring %in% c(1, 4, 5), "elev", "amb"))
  id <- ring:plot
})

#######################
# organise data frame #
#######################

# all spp----
veg.face <- within(vdf, {
  co2 <- factor(ifelse(ring %in% c(1, 4, 5), "elev", "amb"))
  block <- recode(ring, "1:2 = 'A'; 3:4 = 'B'; 5:6 = 'C'")
  id <- ring:plot
})
SiteName <- c("year", "block", "ring", "co2", "plot", "id", "position", "cell")
SppName <- names(veg.face)[!names(veg.face) %in% SiteName]

# plot sum
PlotSumVeg <- ddply(veg.face, .(year, block, co2, ring, plot, id), function(x) colSums(x[, SppName]))

# ring sum
RingSumVeg <- ddply(PlotSumVeg, .(year, block, co2, ring), function(x) colSums(x[, SppName]))

# PFG matrix----

# plot
PlotSumPFGMatrix <- dcast(year + block + co2 + ring + plot ~ PFG, 
                          data = subset(veg, !is.na(PFG)), sum)
colSums(PlotSumPFGMatrix[,6:13])

# remove lichen, also add interaction term
PlotSumPFGMatrix <- within(PlotSumPFGMatrix, {
  Lichen = NULL
  c3_4 = NULL
  id = ring:plot
  yco = year:co2
})

PFGName <- c("c3", "c4", "legume", "moss", "Non_legume", "wood")

# ring
RingSumPFGMatrix <- ddply(PlotSumPFGMatrix, .(year, block, ring, co2, yco), 
                          function(x) colSums(x[, PFGName]))
  

# Diversity & eveness----
vegDF <- PlotSumVeg[, SppName]
siteDF <- PlotSumVeg[, !names(PlotSumVeg) %in% SppName]

DivDF <- within(siteDF,{
  H <- diversity(vegDF) # Shannon's index
  S <- specnumber(vegDF) # number of spp
  J <- H/log(S)  # Pielou's evenness
})

```

```{r, results='markup'}
names(EnvVarDF)

# correlations
CorMatrix <- cor(EnvVarDF[c(-1, -2)], use = "pairwise.complete.obs")
corrplot(CorMatrix, tl.cex = .8)
# some values are really redundant so remove. Also some of them are hard to
# interpret so remove. e.g. EC, Theta75
RmVar <- c("silt", "clay", "OrganicC", "TotalP_CM",
           "Theta5", "Theta30", "Theta75", "EC", 
           "T5", "T10", "T20", "T30", "T50", "T100")
EnvVarDF <- EnvVarDF[, !names(EnvVarDF) %in% RmVar]
CorMatrix <- cor(EnvVarDF[c(-1, -2)], use = "pairwise.complete.obs")
corrplot(CorMatrix)

# some of the variables are not complete for three years

# Variables measured only in the 1st year---
naCol_1stYear <-cbind(EnvVarDF[, c("year", "ring")], 
                      EnvVarDF[, apply(subset(EnvVarDF, year == 2014),
                                       2, function(x) any(is.na(x)))])
# these are all soil variable and shouldn't change dramatically year by year so
# just repeat the 1st year values
NewnaCol <- ldply(1:3, function(...) subset(naCol_1stYear, year == 2013))

# replace na columns with new columns
EnvVarDF[, names(NewnaCol)[c(-1, -2)]] <- NewnaCol[, c(-1, -2)]

# Variables measured only in the 1 and 2nd years----
naCol_2ndYear <-cbind(EnvVarDF[, c("year", "ring")], 
                      EnvVarDF[, apply(EnvVarDF, 2, function(x) any(is.na(x)))])
# these variables may vary year by year
```

```{r, results='markup', fig.height=3.5, fig.width=6}
###########################
# Analyse 3-year data set #
###########################
naCol_2ndYear
# these variables may vary year by year. so remove them for the time being
EnvDF_3df <- EnvVarDF[, apply(EnvVarDF, 2, function(x) !any(is.na(x)))]

# Performe PCoA----
RngVegdf <- ddply(veg.face, .(year, ring, co2), function(x) colSums(x[, SppName]))
RngSppDF <- RngVegdf[, SppName]
RngSiteDF <- RngVegdf[, !names(RngVegdf) %in% SppName]

PCoA <- cmdscale(d = vegdist(log(RngSppDF + 1), method = "bray"), eig = TRUE, k = 3)
PCoA_SiteScoreDF <- cbind(RngSiteDF, PCoA$points)
names(PCoA_SiteScoreDF)[4:6] <- paste0("PCoA", 1:3)

# Fit environmental variables----
# 1st two axes
efLst <- llply(2:3, function(x) envfit(PCoA$points[, c(1, x)], EnvDF_3df[, c(-1, -2)], permu = 999))
efLst
par(mfrow = c(1, 2), mar = c(5, 5, 1, 0))
plot(PCoA2 ~ PCoA1, data = PCoA_SiteScoreDF, type = "n")
d_ply(PCoA_SiteScoreDF, .(year, ring), function(x) {
  points(PCoA2 ~ PCoA1, col = ring, pch = as.numeric(year), data = x, cex = 1.5)
})
plot(efLst[[1]], p.max = .05, cex = .7)
legend("bottomleft", col = c(1:6), pch = c(rep(19, 6)), legend = paste("Ring", 1:6), 
       bty = "n", cex = .7)
legend("topleft", pch = c(1:3), legend = paste("Year", 1:3), bty = "n", cex = .7)

plot(PCoA3 ~ PCoA1, data = PCoA_SiteScoreDF, type = "n")
d_ply(PCoA_SiteScoreDF, .(year, ring), function(x) {
  points(PCoA3 ~ PCoA1, col = ring, pch = as.numeric(year), data = x, cex = 1.5)
})
plot(efLst[[2]], p.max = .05, cex = .7)


```


