# restore required packages
library(checkpoint)
checkpoint("2015-09-30")

library(XLConnect)
library(xlsx)
library(plyr)
library(ggplot2)
library(reshape)
library(reshape2)
library(lme4)
library(car)
library(mvabund)
library(proto)
library(vegan)
library(BiodiversityR)
library(gmodels)
library(nlme)
library(contrast)
library(effects)
library(lmerTest)
library(candisc)
library(MASS)
library(lubridate)
library(visreg)
library(lubridate)
library(HIEv, lib.loc = "/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library(dplyr)
library(scales)
library(corrplot)
library(RVAideMemoire)
library(pbkrtest)
