# restore required packages
# library(checkpoint)
# checkpoint("2015-09-30")
# checkpoint("2016-03-15")

library(XLConnect)
library(xlsx)
library(plyr)
library(ggplot2)
library(reshape)
library(reshape2)
library(lme4)
library(car)
library(mvabund)
library(proto)
library(gmodels)
library(nlme)
library(contrast)
library(effects)
library(lmerTest)
library(candisc)
library(MASS)
library(lubridate)
library(visreg)
library(lubridate)
library(dplyr)
library(tidyr)
library(corrplot)
library(RVAideMemoire)
library(pbkrtest)
library(corrplot)
library(gridExtra)
library(MuMIn)
library(broom)
library(pander)
library(data.table)
library(vegan)

library(HIEv)