# restore required packages
library(checkpoint)
checkpoint("2015-09-30")

library(XLConnect)
library(xlsx)
library(plyr)
library(ggplot2)
library(reshape)
library(reshape2)
library(lme4)
library(car)
library(mvabund)
library(proto)
library(vegan)
library(gmodels)
library(nlme)
library(contrast)
library(effects)
library(lmerTest)
library(candisc)
library(MASS)
library(lubridate)
library(visreg)
library(lubridate)
library(dplyr)
library(scales)
library(corrplot)
library(RVAideMemoire)
library(pbkrtest)

# HIEv
.libPaths("/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library(HIEv)

# checkpoint doesn't support library(BiodiversityR)
# library(BiodiversityR) is not supported by the current verison of R (3.2.3)
